spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 20
  jackson:
    deserialization:
      fail-on-numbers-for-enums: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
